# Generated by Django 6.0 on 2025-12-22 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session_payment_unique_paid_payment_per_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cancelled', models.BooleanField(default=False)),
                ('override_start_time', models.TimeField(blank=True, null=True)),
                ('override_end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exception de session',
                'verbose_name_plural': 'Exceptions de sessions',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_paid_payment_per_month',
        ),
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.room', verbose_name='Salle (override)'),
        ),
        migrations.AddField(
            model_name='sessionexception',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='core.coursegroup'),
        ),
        migrations.AddField(
            model_name='sessionexception',
            name='override_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.room'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexception',
            unique_together={('course_group', 'date')},
        ),
    ]
