# Generated by Django 5.2.15 on 2026-06-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sessionexception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_manually_edited',
            field=models.BooleanField(default=False, verbose_name='Modifié manuellement'),
        ),
    ]
