# Generated by Django 5.2.15 on 2026-06-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_session_is_manually_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'ordering': ['name'], 'verbose_name': 'Groupe de cours', 'verbose_name_plural': 'Groupes de cours'},
        ),
        migrations.AlterUniqueTogether(
            name='coursegroup',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.room', verbose_name='Salle'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseGroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi'), ('SUN', 'Dimanche')], max_length=3, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.coursegroup', verbose_name='Groupe de cours')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='core.room', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Horaire de groupe',
                'verbose_name_plural': 'Horaires de groupe',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.coursegroupschedule'),
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='room',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='schedule_day',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='start_time',
        ),
    ]
