# Generated by Django 5.2.15 on 2026-06-15 13:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_coursegroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('MONTHLY_SALARY', 'Salaire mensuel fixe'), ('HOURLY_RATE', 'Taux horaire'), ('PER_LESSON', 'Par leçon / séance'), ('PER_STUDENT', 'Par élève inscrit'), ('REVENUE_SHARE', "Part du chiffre d'affaires (%)"), ('SALARY_BONUS', 'Salaire + Prime'), ('SALARY_OVERTIME', 'Salaire + Heures supplémentaires'), ('FREELANCER', 'Freelance (devis libre)')], default='HOURLY_RATE', max_length=20, verbose_name='Méthode de paiement')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Utilisé pour: Salaire fixe, Salaire+Prime, Salaire+HS', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salaire de base (DH/mois)')),
                ('hourly_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si vide, utilise le taux horaire du profil professeur', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taux horaire spécifique (DH/h)')),
                ('rate_per_lesson', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarif par séance (DH)')),
                ('rate_per_student', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarif par élève (DH)')),
                ('revenue_share_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ex: 40 pour 40%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='% du CA reversé')),
                ('default_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prime par défaut (DH)')),
                ('default_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Retenue par défaut (DH)')),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Ex: 1.5 = 150% du taux horaire', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Multiplicateur heures sup.')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='RIB / Compte bancaire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='core.teacher', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Configuration de paiement',
                'verbose_name_plural': 'Configurations de paiement',
            },
        ),
        migrations.CreateModel(
            name='TeacherPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('sessions_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de séances')),
                ('lessons_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de leçons')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'élèves")),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Heures travaillées')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Heures supplémentaires')),
                ('revenue_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='CA de référence (DH)')),
                ('payment_method_used', models.CharField(blank=True, max_length=20, verbose_name='Méthode utilisée')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant de base (DH)')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Prime (DH)')),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Retenue (DH)')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Paiement HS (DH)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total net (DH)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Créé par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='core.teacher', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-period_year', '-period_month', 'teacher__name'],
                'unique_together': {('teacher', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='TeacherPayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Heures')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Taux (DH)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant (DH)')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.teacherpayroll', verbose_name='Fiche de paie')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Ligne de paie',
                'verbose_name_plural': 'Lignes de paie',
                'ordering': ['date', 'id'],
            },
        ),
    ]
