# Generated by Django 5.2.15 on 2026-06-15 14:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher_payroll_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherpayroll',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teacherpayroll',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherpayrollline',
            name='payroll',
        ),
        migrations.RemoveField(
            model_name='teacherpayrollline',
            name='session',
        ),
        migrations.AddField(
            model_name='teacher',
            name='payment_method',
            field=models.CharField(choices=[('HOURLY', 'Taux horaire'), ('PERCENTAGE', 'Part des gains (pourcentage des gains de la classe)')], default='PERCENTAGE', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='payment_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Part des gains (%)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarif horaire (DH)'),
        ),
        migrations.DeleteModel(
            name='TeacherPaymentConfig',
        ),
        migrations.DeleteModel(
            name='TeacherPayroll',
        ),
        migrations.DeleteModel(
            name='TeacherPayrollLine',
        ),
    ]
