# Generated by Django 5.2.15 on 2026-06-15 14:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_teacherpayroll_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('100.00'), max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarif horaire (DH)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Part des gains (%)'),
        ),
    ]
