# Generated by Django 5.2.15 on 2026-06-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_teacher_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.session', verbose_name='Session'),
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi'), ('SUN', 'Dimanche')], max_length=3, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Début disponibilité')),
                ('end_time', models.TimeField(verbose_name='Fin disponibilité')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.teacher', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Disponibilité professeur',
                'verbose_name_plural': 'Disponibilités professeurs',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
