# Generated by Django 5.2.15 on 2026-06-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scheduling_upgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='end_time',
            field=models.TimeField(verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='start_time',
            field=models.TimeField(verbose_name='Heure de début'),
        ),
    ]
