# Generated by Django 5.2.15 on 2026-06-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification_alter_teacheravailability_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='sessionexception',
            name='override_day',
            field=models.CharField(blank=True, choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi'), ('SUN', 'Dimanche')], max_length=3, null=True, verbose_name='Nouveau jour'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Prévu'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=10),
        ),
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
    ]
