# Generated by Django 5.2.15 on 2026-06-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_notification_sessionexception_override_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionexception',
            name='override_day',
        ),
    ]
