# Generated by Django 5.2.15 on 2026-06-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_sessionexception_override_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_sessions', to='core.teacher', verbose_name='Enseignant remplaçant'),
        ),
    ]
