# Generated by Django 5.2.15 on 2026-06-18 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_session_substitute_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine date de paiement'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'inscription effective"),
        ),
    ]
