# Generated by Django 5.2.15 on 2026-06-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_enrollment_next_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='registration_date',
        ),
    ]
