# Generated by Django 5.2.15 on 2026-06-19 18:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_enrollment_next_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine date de paiement'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='session_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('100.00'), max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarif par session (DH)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='payment_method',
            field=models.CharField(choices=[('HOURLY', 'Taux horaire'), ('PERCENTAGE', 'Part des gains (pourcentage des gains de la classe)'), ('SESSION', 'Tarif par session')], default='PERCENTAGE', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
