# Generated by Django 5.2.15 on 2026-06-19 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_level_student_level_alter_coursegroup_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_groups', to='core.level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.level', verbose_name='Niveau scolaire'),
        ),
    ]
