"""
Django settings for school_erp project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@(cwmj-)e)39(8ty(k5us(ywqt!(5u2zc^oes3$b4exz&p@7b*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.import_export",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'import_export',
    'django_filters',
    'django_extensions',
    "django_htmx",

    'core',
]


UNFOLD = {
    "SITE_TITLE": "Admin Centre Tonaroz",
    "SITE_HEADER": "🎓 Centre Tonaroz",
    "SITE_SYMBOL": "school",           # Material symbol name
    "SHOW_HISTORY": True,
    "DARK_MODE": True,

    # ── Inject our custom CSS after Unfold's CSS ──
    "STYLES": [
        lambda request: static("admin/css/school_admin.css"),
    ],

    # ── Custom sky blue colour palette matching the poster ──
    "COLORS": {
        "font": {
            "subtle-light":   "107 114 128",   # gray-500
            "subtle-dark":    "156 163 175",   # gray-400
            "default-light":  "17 24 39",      # gray-900
            "default-dark":   "243 244 246",   # gray-100
            "important-light":"0 0 0",
            "important-dark": "255 255 255",
        },
        "primary": {
            "50":  "240 249 255",   # sky-50
            "100": "224 242 254",   # sky-100
            "200": "186 230 253",   # sky-200
            "300": "125 211 252",   # sky-300
            "400": "56 189 248",    # sky-400
            "500": "14 165 233",    # sky-500
            "600": "2 132 199",     # sky-600  ← main (sky-600)
            "700": "3 105 161",     # sky-700
            "800": "7 89 133",      # sky-800
            "900": "12 74 110",     # sky-900
            "950": "8 47 73",       # sky-950
        },
    },

    # ── Sidebar navigation groups with icons ──
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Tableau de bord",
                "separator": False,
                "items": [
                    {
                        "title": "Accueil",
                        "icon": "home",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Élèves & Inscriptions",
                "separator": True,
                "items": [
                    {
                        "title": "Élèves",
                        "icon": "school",
                        "link": reverse_lazy("admin:core_student_changelist"),
                    },
                    {
                        "title": "Paiements",
                        "icon": "payments",
                        "link": reverse_lazy("admin:core_payment_changelist"),
                    },
                    {
                        "title": "Présences",
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:core_attendance_changelist"),
                    },
                ],
            },
            {
                "title": "Organisation",
                "separator": True,
                "items": [
                    {
                        "title": "Groupes de cours",
                        "icon": "groups",
                        "link": reverse_lazy("admin:core_coursegroup_changelist"),
                    },
                    {
                        "title": "Professeurs",
                        "icon": "person_book",
                        "link": reverse_lazy("admin:core_teacher_changelist"),
                    },
                    {
                        "title": "Salles",
                        "icon": "meeting_room",
                        "link": reverse_lazy("admin:core_room_changelist"),
                    },
                    {
                        "title": "Niveaux",
                        "icon": "school",
                        "link": reverse_lazy("admin:core_level_changelist"),
                    }
                ],
            }
        ],
    },
}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
    'core.middleware.AdminOnlyMiddleware',
]

ROOT_URLCONF = 'school_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.conflicts_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        "OPTIONS": {
            "timeout": 20,  # seconds
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = "Africa/Casablanca"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = 'core:cockpit'
LOGOUT_REDIRECT_URL = '/admin/login/'


# Settings for school ERP
SCHOOL_NAME = "Centre Tonaroz"
SCHOOL_ADDRESS = "Rue Marrakech Im 16 Ap N 3 2EME ETAGE Khouribga"
SCHOOL_PHONE = "0707477911 / 0661569522"
SCHOOL_EMAIL = "contact@tonaroz.com"

